#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 14 15:37:15 CET 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim simulation_Perceptron_behav -key {Behavioral:sim_1:Functional:simulation_Perceptron} -tclbatch simulation_Perceptron.tcl -view /home/lespiaucq/5SEE/Implementation Materielle Perceptron/Perceptron_network/MLP/simulation_Perceptron_CONFIG.wcfg -log simulate.log"
xsim simulation_Perceptron_behav -key {Behavioral:sim_1:Functional:simulation_Perceptron} -tclbatch simulation_Perceptron.tcl -view /home/lespiaucq/5SEE/Implementation Materielle Perceptron/Perceptron_network/MLP/simulation_Perceptron_CONFIG.wcfg -log simulate.log

